// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalCqGZco4WJwPNeJCgvV0_GCqIryfNBA',
    appId: '1:198160803666:web:649e62f9147c541a393c8b',
    messagingSenderId: '198160803666',
    projectId: 'act15-c41df',
    authDomain: 'act15-c41df.firebaseapp.com',
    storageBucket: 'act15-c41df.firebasestorage.app',
    measurementId: 'G-CJPL26F324',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Z1M_DbGjApmqgQPnRpWd099EXVkxPx4',
    appId: '1:198160803666:android:d494bde80dc76bca393c8b',
    messagingSenderId: '198160803666',
    projectId: 'act15-c41df',
    storageBucket: 'act15-c41df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJcAdwQp7hkTnGA4O4k7TVhkrt-v4y0U',
    appId: '1:198160803666:ios:9235041c0cc77f3f393c8b',
    messagingSenderId: '198160803666',
    projectId: 'act15-c41df',
    storageBucket: 'act15-c41df.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJcAdwQp7hkTnGA4O4k7TVhkrt-v4y0U',
    appId: '1:198160803666:ios:9235041c0cc77f3f393c8b',
    messagingSenderId: '198160803666',
    projectId: 'act15-c41df',
    storageBucket: 'act15-c41df.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBalCqGZco4WJwPNeJCgvV0_GCqIryfNBA',
    appId: '1:198160803666:web:95bceec05bb637f8393c8b',
    messagingSenderId: '198160803666',
    projectId: 'act15-c41df',
    authDomain: 'act15-c41df.firebaseapp.com',
    storageBucket: 'act15-c41df.firebasestorage.app',
    measurementId: 'G-J2R9Y01VHX',
  );
}
